### ISSUE TITLE
Add Intel 12th gen [Alder Lake] CPUs

### ISSUE THREAD

**Issue by maduesi** [jbcarreon123/Win11CompChk#5]
The Core Gen 12 Intel CPUs are missing, my proposition:

type %temp%\CPUC.log | findstr /c:"Core(TM) i5-12600K " >nul 2>&1 && set "CPUComp=Compatible"  && goto cpufn 
type %temp%\CPUC.log | findstr /c:"Core(TM) i5-12600KF " >nul 2>&1 && set "CPUComp=Compatible"  && goto cpufn 
type %temp%\CPUC.log | findstr /c:"Core(TM) i7-12700K " >nul 2>&1 && set "CPUComp=Compatible"  && goto cpufn 
type %temp%\CPUC.log | findstr /c:"Core(TM) i7-12700KF " >nul 2>&1 && set "CPUComp=Compatible"  && goto cpufn 
type %temp%\CPUC.log | findstr /c:"Core(TM) i9-12900K " >nul 2>&1 && set "CPUComp=Compatible"  && goto cpufn 
type %temp%\CPUC.log | findstr /c:"Core(TM) i9-12900KF " >nul 2>&1 && set "CPUComp=Compatible"  && goto cpufn 
type %temp%\CPUC.log | findstr /c:"Core(TM) i7-12700KF " >nul 2>&1 && set "CPUComp=Compatible"  && goto cpufn 

source of compatible CPUs: https://docs.microsoft.com/de-de/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors

**Comment by jbcarreon123** [comment]
Thanks. I will add it to the Win11CompChk v6.

**Comment by jbcarreon123** [comment]
This was added in v5.4.0. Thanks for submitting this issue!
