### ISSUE TITLE
Change OS Arch code

### ISSUE THREAD

**Issue by maduesi** [jbcarreon123/Win11CompChk#6]
I've tested this with several Windows 10 systems. Some systems output "wmic OS get OSArchitecture"

32-bit or 64-bit
and other
32-Bit or 64-Bit

That means we have to look for all four spellings in the OSArch.log (wmic OS get OSArchitecture>% temp% \ OSArch.log). My proposition:

type %temp%\OSArch.log | findstr /i /c:"32-bit" >nul 2>&1 && ( set "OSA=32-bit")
type %temp%\OSArch.log | findstr /i /c:"64-bit" >nul 2>&1 && ( set "OSA=64-bit")

OR

type% temp% \ OSArch.log | findstr / c: "32-Bit"> nul 2> & 1 && (set "OSA = 32-bit")
type% temp% \ OSArch.log | findstr / c: "32-bit"> nul 2> & 1 && (set "OSA = 32-bit")
type% temp% \ OSArch.log | findstr / c: "64-Bit"> nul 2> & 1 && (set "OSA = 64-bit")
type% temp% \ OSArch.log | findstr / c: "64-bit"> nul 2> & 1 && (set "OSA = 64-bit")

**Comment by jbcarreon123** [comment]
Thanks for the bug, I will add it to the v6 update.

**Comment by jbcarreon123** [comment]
This was fixed in v5.4.0. Thanks for submitting this issue!
